language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  - npm i @microservices/cli
script:
  - npx oms build
  - |
    output="$(npx oms run --silent scrape \
    -a url="https://oms.hudson.dev/fixtures/html5-bare-minimum.html" \
    -e SCRAPER_API_KEY=$SCRAPER_API_KEY \
    -e SCRAPER_API_ORIGIN=$SCRAPER_API_ORIGIN | jq -c .)"
    if [ "$output" != '{"html":"<!DOCTYPE html><title>hello</title>\n"}' ] ; then echo "$output"; exit 1; fi
env:
  global:
    - secure: Og6yoQ3E+C74Mftu1Xky5QyCRHpivy5d8NVftmEhrui8D4rRyet6RjdpQaaSL8ZzC0k89qQFhgu1rUMn+5kfWxZB/67cM53NL6/CtlavBLhSy7ipRwEUXjzh8A5/cVGVMk7Gl3HkA2keveKanbHQuhTTbgr4ZZTiNldhGhoH0e/H045G/HSgAqXXj5v538ZqisyGRrU599R1u5TuhtKjpd/E6+1CKbliA4K8UGYg1TISF0pT2tnmafmDfB5s65E5Q6mvWWE/hIiBUK3RVaVw+uFMILNJBX/66K22AquKj7MV+CAMXcqkXbJUnLPVUSJmj2fWOtKZh18l2Lc7Ex71AjWLY1QSo+UpPtmHLpkEXLYXbf4VPnEdh2IoO1QCQcWYAZ7xlP/m/IJxw8GP1JUXd3uM7pIfiR8ADXim4EsvZfjoBNt5Mxqhph2b4QhPbMPRxYw/qVO2sk2sY//0x6Mwiit0QmorMcJ7RN2a/3Cvcc1y+3XztZc8VYGBGiO8lUHrhC4NRkxdsr2C3BwdRMPaCvuASzSpZwH1qRLi0AeGLZ1WKiFdLSuNJ1Nw5naym9eTnO3ET0PdkeoETXeZl99w6CHRw/DrCfq+4F//206gv9n4H/nLeEKHLdL9OCeUlFg8CGU6S7uVRF3ra/sv6G253b9oQg7wsAEDitcUDASiotA=
    - secure: QLh6USRtficrrrkFzfJiLN0VWsLjmitMzeWSrpMmGaIykWy65w2s3IsG/pUZQ0Ciwcj8Dhpkvsfubp0P4zlvcYUPUxxb5L3exId/XalyrTx8bIJjr1xXvtWjHvrR6SbEILfhVfLqAG7oa3BXdS9Teligt4YZAhBF7HaNHf/qMSUHsyMzUocZfhtD5Gb+uDE3WI/5Rpl3soVKePe8kSp1SQR5I6PDre7COc/eSLMPIFYkCmoJ+Qo/YRiFwU62wZaZwT+/WlnKcVm3Rg426O9JM1MUctpIfeanM1hdzw30ZM/Buo+YYjpJ8ozVAXtGMgj30vYWpFBf/Ezm6VcAnXTBGLfULiAth4++V9fnsxiofvRcD+gIkyverB20YFaA49SQyIXwIYLB6cqSpQpfgWRMTWVH9jWXNodlrvp9H1U8kmS69nG8CDkLd1iJuBhBCOBIj6aX2q+WOLT67KzWG9RtPSJTe9ZFcgwDTJDV64vrrY8aysteeFQjpY4En3UEQhiyMSSrDnnmdovYCr7Ex/i/q4mgL0wR6jYYZVmyqzxSu78FT5fITGoBeTqV8n2axKG0wUo8nU3djCHkFKAYLIQqRUOiXvCTS77A+3ZM1NgnRaN4bKoGNA8ywNds64qYUayb259iitm0q5ZwGXFBmslWUCV89RmtL4W5Eh/Zrf4lkWQ=
